DROP TABLE liquidaciones;
DROP TABLE trabajadores;
DROP TABLE departamentos;


CREATE TABLE departamentos(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL

);

CREATE TABLE trabajadores(
    ID SERIAL PRIMARY KEY,
    RUT VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    ID_DEPARTAMENTO INT, 
    FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES departamentos(ID)
);

CREATE TABLE liquidaciones(
    ID SERIAL PRIMARY KEY,
    DRIVE VARCHAR(255),
    ID_TRABAJADORES INT,
    FOREIGN KEY(ID_TRABAJADORES) REFERENCES trabajadores(ID)

);






