DROP TABLE prueba_alumnos;
DROP TABLE pruebas;
DROP TABLE cursos_alumnos;
DROP TABLE alumnos;
DROP TABLE cursos;
DROP TABLE profesores;
DROP TABLE departamentos;


CREATE TABLE alumnos(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(30),
    RUT VARCHAR(15)
);

CREATE TABLE cursos(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(20)
);

CREATE TABLE departamentos(
    ID SERIAL PRIMARY KEY,
    NOMBRE_DEPARTAMENTO VARCHAR(30)
);

CREATE TABLE profesores(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(20),
    ID_DEPARTAMENTO INT,
    FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES departamentos(ID)
);

CREATE TABLE cursos_alumnos(
    ID_CURSOS INT,
    ID_ALUMNOS INT,
    FOREIGN KEY(ID_CURSOS) REFERENCES cursos(ID),
    FOREIGN KEY(ID_ALUMNOS) REFERENCES alumnos(ID)
);

CREATE TABLE pruebas(
    ID SERIAL PRIMARY KEY,
    NOMBRE_PRUEBA VARCHAR (25)
);

CREATE TABLE prueba_alumnos(
    ID_ALUMNOS INT,
    ID_PRUEBAS INT,
    ID_PROFESORES INT,
    PUNTAJE INT,
    FOREIGN KEY(ID_ALUMNOS) REFERENCES alumnos(ID),
    FOREIGN KEY(ID_PRUEBAS) REFERENCES pruebas(ID),
    FOREIGN KEY(ID_PROFESORES) REFERENCES profesores(ID)
);
